### ISSUE TITLE
Test installation on Debian 9

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#101]
Since the new PalMA is intended to run on the current stable version of Debian and Raspbian, we must test installation and usage on Stretch.

**Comment by stweil** [comment]
Related (but could also be handled as separate issue): PalMA currently uses a start script in `/etc/init.d`. Debian 9 still supports that System V interface, but it is deprecated. The new start mechanism is based on `systemd` and has several advantages. Using it for PalMA would be good.

**Comment by dennmuel** [comment]
Got everything up and running so far. Needed to give Raspbian a few second more time to get started. Startup via systemd is implemented.
