### ISSUE TITLE
Style contact form in iframe 

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#107]
Change to transparent background and style with pure-min.css where necessary.

**Comment by wagneral** [comment]
Switched background-color.

**Comment by wagneral** [comment]
Bootstrap.css (//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css) is already included. So what would be a use case for pure-min.css (//unpkg.com/purecss@1.0.0/build/forms-min.css) ?

**Comment by dennmuel** [comment]
I was beginning styling the form, but couldn't finish. I wanted to try using pure-min.css because we already use this for buttons, forms etc. in the UI. Thought it might save us some work to give the form elements the same classes that are already in use in the UI.

**Comment by wagneral** [comment]
Thanks, seems to be a good point. Let's try to find a decision after the upcoming release. We should check all the implemented frameworks (js, css, ...) for conflicts or duplicates. We should try to simplify the code where possible ...
