### ISSUE TITLE
Rollout

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#108]
Some things to consider when rolling out the new release (just from the top of my head;  additions welcome):

To do manually:
- Test old and new release on NUC and RPi that are upgraded to Stretch and php7 (update install.md accordingly) --> _**Done** (Some important paths have changed, e.g. for starting the vnc server, with php7. So I added a functionality to check whether php5 or 7 is installed.)_
- Remove unwanted packages on model machines and provide a list of wanted packages for cfengine --> _**Done** (Well, RPi hung itself while cleaning, but since all the other RPis have not been cleaned up either, I don't see why we should troubleshoot this right now.)_

Automated in _experimental_ `scripts/instal_palma.sh`:
- Upgrade all machines to stretch completely unattendedly (keeping config files etc.)--> _**Done**_
- Install necessary packages (midori, feh, php7, etc.) --> _**Done**_
- Git pull the new PalMA release  --> _**Done**_
- Add new lines to palma.ini (institution url)  --> _**Done**_
- Remove old and copy new startscript (systemd)  --> _**Done**_
- Create new language files  --> _**Done**_
- Make sure all files have right permissions  --> _**Done**_

The script can be used for upgrading an existing and setting up a completely new palma station. Please [see the script](https://github.com/UB-Mannheim/PalMA/blob/palma-redesign/scripts/install_palma.sh) for details (and help making it better).

To take care off:
- Automate webserver configuration (e.g. Make sure nginx gets the new php7 paths in `/etc/nginx/sites-enabled/default`) --> _**Is that necessary / possible without too much effort?**_
- Remove unwanted packages (via cfengine with lists provided in /examples)

**Comment by dennmuel** [comment]
Tested update script successfully twice in virtual machine, that is on the current status of our regular palma stations (excluding rpi so far).

**Comment by wagneral** [comment]
Nice.

**Comment by dennmuel** [comment]
After our local rollout we'll need to remove the piwik-part and the upgrade part from the installation script. Since we only need to change the webserver config of five machines, we will exclude this from the automation for now and discuss if and how we should implement it for users other than UB Mannheim.

**Comment by wagneral** [comment]
After excluding the named files we can draft a new Release.

**Comment by dennmuel** [comment]
After some problems regarding debian upgrade, that Stefan was so nice to handle, I think we can consider this issue closed. Yet I'm still wondering, if and how our stations get updates from the master branch automatically.

**Comment by stweil** [comment]
The stations only get Debian security updates automatically. PalMA updates were always installed manually (of course supported by a script which repeats a defined action for all stations).

**Comment by wagneral** [comment]
For upcoming releases and software updates we should think about this issue again.
