### ISSUE TITLE
Plugin Management

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#112]
While integrating the **Piwik** statistics the idea for a plugin management (kind of webhooks) was born. Therefore a `plugin/` directory was created. 

In future use this directory will be scanned for files. Every file represents a plugin that will be included in `index.php` if activated.

Ideas for that kind of plugins can be
- HTML Templates as already implemented **Piwik**,  or another kind of reports like a **Tracking** function to gain information about installed PalMA stations
- send custom **Events** (uploaded file, shared screen) to database or server when calling defined action to monitor usage 
- **Javascript** Snippets, Libraries or Templates needed for a custom UX or additional **AJAX** functions
- **Eastereggs**, as already planned
- additional functions like a **out for lunch** button, that keeps PalMA from automaitcally logging out users during a coffee or cigarette break, that lasts longer than 15 minutes

**Comment by dennmuel** [comment]
Possible solution for eastereggs?

**Comment by wagneral** [comment]
Yes, of course. Tanks. Added it above.
