### ISSUE TITLE
Check apt-libraries

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#119]
When uploading contributions like images they can be rotated left or right. In some cases this is not possible. This seems to be an unsolved dependency between `apt `packages. 

The `feh `package not necessarily brings all needed components. We have to analyze which other packages are needed.

**Comment by wagneral** [comment]
See the following contribution for needed package: https://github.com/UB-Mannheim/PalMA/commit/26da168cff3f67532a1db270a3c97cd84d521a77#diff-8f5f744f9619de7863233927960402e4

**Comment by stweil** [comment]
> +libturbojpeg0:i386

That does not look correct. We do not suggest using 32 bit Debian installations for modern Intel processors. The correct dependency can be seen in the [package description](https://packages.debian.org/stretch/feh) for `feh`: it suggests `libjpeg-progs` which resolves to `libjpeg-turbo-progs`.

**Comment by wagneral** [comment]
Ok, we'll consider that. Thank you.

**Comment by stweil** [comment]
I added `libjpeg-turbo-progs` to the list of required packages now and installed it. Could you please repeat your test cases to see whether that fixes this issue?

**Comment by wagneral** [comment]
Solution works.
