### ISSUE TITLE
libjpeg-turbo not loaded for Mac VNC connection

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#140]
Nutzerhinweis per Mail:

Trotz mehrmaligem Herunterladen und Installieren von VineServer konnte keine Verbindung vom Mac zu PalMA hergestellt werden.

`2018-03-05 12:14:48 +0000 Starting Vine Server 5.1.0(1703281043) -rfbport 0 -desktop mobile-193-180.wlan.uni-mannheim.de (ASMH) -donotloadproxy -rfbnoauth -restartonuserswitch N -UnicodeKeyboard 0 -keyboardLoading N -pressModsForKeys N -EventTap 3 -EventSource 2 -swapButtons -rendezvous Y dyld: Library not loaded: /sw/lib/libjpeg-turbo/lib/libturbojpeg.dylib Referenced from: /Applications/Vine Server.app/Contents/MacOS/OSXvnc-server Reason: image not found`

**Comment by stweil** [comment]
This was fixed in the [latest release](https://github.com/stweil/OSXvnc/releases/tag/V5_2_1). Maybe some PalMA stations still deliver an old release?

**Comment by dennmuel** [comment]
You were right. The BWL stations were still delivering their local dmg instead of linking to our homepage. Should be resolved now.

**Comment by stweil** [comment]
Thank you, Dennis.
