### ISSUE TITLE
Midori does not play youtube videos

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#142]
Midori does not display youtube videos that are handed to it by the url input field. It does not work either when using midori "manually" (outside of palma context). However it does work using Firefox.

We need to determine if this affects youtube only or any kind of video platform and why it happens at all. Possible problems could be missing codecs or how midori handles HTML 5 videos or ...?

**Comment by stweil** [comment]
I‌ have just run `midori "https://www.youtube.com/embed/C0DPdy98e4c?autoplay=1&VQ=default"` on our first PalMA station, and it worked – the video was shown.

**Comment by dennmuel** [comment]
Interesting, thanks for the info. I tested on two stations in the Learning Center (lc14 and lc15), with no success as described above. Since I don't know which machine you mean by "our first PalMA station", could you please look into possible differences between this machine and our productive systems?

**Comment by stweil** [comment]
The Gtk message is unrelated. The canberra module is used to generate sound events for certain Gtk events like opening or closing a window and others.

**Comment by stweil** [comment]
Installation of `gstreamer1.0-libav` seems to fix playing videos on lc14.

**Comment by dennmuel** [comment]
Thank you very much! We should give this some testing (note to self: what about the RPis?) and review the list of required packages.

**Comment by stweil** [comment]
As soon as you can confirm that it fixes lc15, too, I suggest to add it to the list of required packages (also in our cfengine configuration, so it gets installed automatically on all stations).

**Comment by dennmuel** [comment]
Exactly my thoughts ;)

**Comment by dennmuel** [comment]
Confirmed and deployed.
