### ISSUE TITLE
List of complete and partial localizations

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/PalMA#17]
Currently it is hard to see if a localization is complete or only partial.

**Comment by stweil** [comment]
Just look for empty msgstr lines in the non-English po files. This command shows missing translations:

    git grep -l 'msgstr ""' locale/*/LC_MESSAGES/*.po|grep -v en_US|xargs git grep -B 2 'msgstr ""'

There are also translator tools with graphical user interfaces which help to find and translate missing text.
Currently all languages have missing translations.

**Comment by stweil** [comment]
Ah, sorry, for long texts (which are split across several lines) the above method does not work. This command line does a better job:

    git grep -l 'msgstr ""' locale/*/LC_MESSAGES/*.po|grep -v en_US|xargs git grep -A 1 -B 2 'msgstr ""'|grep -B3 'po-$'|less

**Comment by kba** [comment]
I wrote a perl script that does this. Current state:

```
al_AL   57.14%   (27 / 63)
ar      42.19%   (37 / 64)
de_DE   96.88%   (2 / 64)
es_ES   92.19%   (5 / 64)
it_IT   93.75%   (4 / 64)
ru_RU   95.31%   (3 / 64)
zh-CN   100.00%  (0 / 64)
```

See #18

**Comment by zuphilip** [comment]
@kba This looks very nice! I suggest to also provide the current state (your first result) as a markdown file, maybe even the detailed results as well. This could motivate students to improve on our current translations.

**Comment by kba** [comment]
Implemented, example: https://github.com/kba/PalMA/blob/dbd3a2418a2030d53e304e464de4bb8983f27d02/TRANSLATIONS.md

**Comment by zuphilip** [comment]
:tada: Thank you very much! :tada:
