### ISSUE TITLE
Some locales break JS

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#188]
Switching to e.g. French locale breaks JS code, the reason being a non-escaped `'` character. Example:
https://github.com/UB-Mannheim/PalMA/blob/a54c9df57faf8e19158e9c024d2b076f466eabde/index.php#L223

Possible solutions would be to escape it either in the locale file or in the code (via either PHP or JS).

**Comment by stweil** [comment]
Would using `htmlspecialchars` fix that?

**Comment by dennmuel** [comment]
No, but `addslashes` seems to do the job.
