### ISSUE TITLE
Update dropzone.js

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/PalMA#208]
The current code uses code which is several years old. More [recent releases of dropzone](https://github.com/dropzone/dropzone/releases) are available and should be used. Of course that requires a compatibility check.

We might also consider using a minimized dropzone.js, or we could remove dropzone.js from the GitHub code and use a package manager to install dropzone.

**Comment by jmechnich** [comment]
Updated to version 5.9.3. Complaints by CodeQL are either gone due to the update, or simply because we are now using the minimized version of the code.
