### ISSUE TITLE
Add demo installation with Docker image

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/PalMA#29]
A Docker image of PalMA could be used for demos and test, but also to add PalMA functionality to simple presentation PCs.

**Comment by wagneral** [comment]
No actions since may 2017: therefore closed.

**Comment by stweil** [comment]
I'd like to keep that open.

**Comment by jmechnich** [comment]
A Dockerfile has been add with tag v1.4.8.
A Docker image can be built and run on the fly e.g. with `docker run -e THEME=ub-mannheim/a3 -h palma-docker --name palma --rm $(docker build -q github.com/UB-Mannheim/PalMA.git)`.

**Comment by dennmuel** [comment]
In the latest version (using chromium on bullseye) an additional flag `--cap-add=ALL` is needed:

`docker run -it -e THEME=ub-mannheim/a3 -h palma-docker --name palma --rm --cap-add=ALL $(docker build -q github.com/UB-Mannheim/PalMA.git)`
