### ISSUE TITLE
Improve communication with PalMA users

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/PalMA#30]
Currently there is only random feedback from
- institiutions which use PalMA
- PalMA users at Mannheim University Library

The list of institutions using PalMA (https://github.com/UB-Mannheim/PalMA/wiki) is also very incomplete.
I invite members of those institutions to add their institution to that list.

Do we need more dedicated communications channels like mailing lists, twitter, ...? Which ones?

**Comment by zuphilip** [comment]
I have seen in [another application](http://editor.citationstyles.org/about/) a `Feedback` button in the application itself:
![feedback-button](https://cloud.githubusercontent.com/assets/5199995/16143138/13f79636-346b-11e6-8db9-f5334f1c1243.png)

which will open a widget:
![uservoice-widget](https://www.uservoice.com/assets/img/widget/widget.png)
The content is saved in a forum and thereby also allowing to give answers.

**Comment by kba** [comment]
Some quick ideas;
* A screencast / video series outlining installation and usage
* Docker container to simplify distribution
* Highlight the advantages vis a vis other solutions, e.g. concerning [security](http://arstechnica.com/security/2016/06/teamviewer-says-theres-no-evidence-of-2fa-bypass-in-mass-account-hack/) and [open standards](https://github.com/UB-Mannheim/PalMA/wiki#was-ist-mit-airplay-oder-miracast)
* Testimonials?
* Short howto articles: PalMA for presentation, Extending your desktop to PalMA, remote desktop with PalMA ...

**Comment by wagneral** [comment]
Good ideas, but what about direct communication e.g. hosting a user meeting?

**Comment by wagneral** [comment]
This issue should be divided into two several terms: 1) feedback & 2) advertising. 

1) Feedback can be realized with a html form contained in an overlay like "faq". Possibly with an integrated upload of Palma log file.

2) To tell the community or friends about Palma, a little share button can be created in the bottom right area of the interface (below help button).

**Comment by wagneral** [comment]
Implemented a contact form and social media sharing buttons. Has to be tested and pulled to master branch when ready.

**Comment by wagneral** [comment]
For sending mails the palma host has to be properly configured, maybe we have to check if all palma hosts already can send mails.
