### ISSUE TITLE
Search and Replace old URLs

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/PalMA#41]
Some of the URLs to the documentation, e.g. http://www.bib.uni-mannheim.de/fileadmin/pdf/ub/LearningCenter/palma-kurzanleitung.pdf changed after our new web launch. Therefore, we should search all of these here and replace them.

**Comment by wagneral** [comment]
Compare to: https://github.com/UB-Mannheim/PalMA/issues/45

**Comment by dennmuel** [comment]
As mentioned before, the issue will be taken on in #45 , therefore closed.
