### ISSUE TITLE
Add configuration option for links to manuals

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#45]
Links to PDF manuals are broken. Currently correct URLs are:
Windows: https://www.bib.uni-mannheim.de/fileadmin/ub/pdf/Anleitungen/KurzanleitungfuerdieBildschirmfreigabe_Windows__.pdf
Windows English: https://www.bib.uni-mannheim.de/fileadmin/ub/pdf/Anleitungen/QuickPalMAManual_Windows_englisch.pdf
MAC: https://www.bib.uni-mannheim.de/fileadmin/ub/pdf/Anleitungen/KurzanleitungfuerdieBildschirmfreigabe_MAC_.pdf

**Comment by stweil** [comment]
The URLs for the manuals are currently included in `index.php` and in all language specific po files. They address pages of the UB Mannheim website which no longer existed after a relaunch of that website. This is fixed now by redirecting the old URLs to the new ones.

There remain some problems which already existed from the beginning and which should be fixed:

* The URLs are the same for all languages, so there is currently no link to the English manual.
* It is much work to replace the URLs for installations other than UB Mannheim.

Maybe the manuals could be added to the PalMA installation as part of the theme. In addition, the language could be added to the filenames, so different manuals for each language would be possible.

**Comment by wagneral** [comment]
Compare to: https://github.com/UB-Mannheim/PalMA/issues/41

**Comment by dennmuel** [comment]
We could have one link in the help section that leads to a PDF file in the theme folder. It could change depending on the selcted user language and lead to the english version as a default.
On the other hand this might be a bit tricky when it comes to changing the files. Perhaps it would be easier to have a link to the PDF on a webserver definable in the ini file?

**Comment by dennmuel** [comment]
Added a link to config that institutions can use for external pdf files, link to a palma section on their website or however they want to provide further information to the user.
