### ISSUE TITLE
URLs containing special characters are not displayed

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#56]
When calling an URL, which leads to a PDF document PalMA only shows an empty window.
Possible reason is a missing extension the PalMA integrated browser neeeds.

**Comment by dennmuel** [comment]
There is a disambiguation for this issue:
In one case the problem seems to be special characters, that get converted to control characters somewhere along the way.
In another case dwb opens a download dialog instead of displaying the file.

**Comment by wagneral** [comment]
Thanks for your detailed comment.

**Comment by dennmuel** [comment]
Example: https://www.uni-mannheim.de/1/presse_uni_medien/pressemitteilungen/2014/Mai/Neues%20Learning%20Center%20der%20UB%20er%C3%B6ffnet/Learning%20Center%201.jpg

This link contains spaces and an umlaut, that get converted to control characters visible above. Pasting the link with control characters into a browser works (they are converted back), but not pasting to the URL field of PalMA. After submitting they URL field gets cleared, but nothing happens.

**Comment by dennmuel** [comment]
Please see and evaluate #80b4e0c.

**Comment by dennmuel** [comment]
Happens again after merging all the testing branches into palma-redesign branch.

**Comment by dennmuel** [comment]
Some URLs with special characters are beeing displayed, but PalMA kind of hangs itself. One needs to "close all windows". The program seems to be stuck in some kind of loop. Gonna look into this...

**Comment by dennmuel** [comment]
Fixed by commits e19c3e8 and 0ce80c3.
