### ISSUE TITLE
Simple download of desktop sharing tool

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#57]
One button for downloading the desktop sharing client should be sufficient. The selection of the chosen client shall fit the user's operating system.
Perhaps it is a good idea to show the download button on the main screen, not only in help & faq section.

**Comment by wagneral** [comment]
Maybe we should offer a short bash script for Linux users for sharing their X display (see command in help and extras) as download as well.

**Comment by stweil** [comment]
The help text already shows the short command line needed for Linux.

**Comment by dennmuel** [comment]
True that, but offering a downloadable file would help unitizing the user interface. Also there are unexperienced Linux users, who don't know or don't want to know about shell commands.
Furthermore we'd have to take on the current state at latest, when/if we have a go at [this vision.](https://github.com/UB-Mannheim/PalMA/projects/2#card-2854132)

**Comment by wagneral** [comment]
First approach can be tested here https://github.com/UB-Mannheim/PalMA/commit/789be14f62611c9069ddd74505d6acb9bccddede

**Comment by wagneral** [comment]
Moved approach from master to testing branch https://github.com/UB-Mannheim/PalMA/blob/8ccfcf8831c39afd985df6f4906b694a1835dce4/test/detect-os.html

**Comment by wagneral** [comment]
2do: Copy linux and mac-vnc file to theme directories.

**Comment by wagneral** [comment]
Files copied, furthermore cleaned up control interface and placed download button on first tab.
