### ISSUE TITLE
Clean up control interface

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#58]
The area below the monitor controls seems to claim to much space compared to the rest of the interface. It would be great if this area could be divided in a section with three (or more) tabs.

These tabs can contain the following elements, that already exist:
 * share
 * upload
 * url

**Comment by dennmuel** [comment]
Download button for screensharing could be included in the first tab ("share") to make it more prominent.

**Comment by wagneral** [comment]
Control interface restructured. Tabs added, download button for screensharing included in first tab. Maybe add a fourth tab later on, for uploaded files. Maybe show uploaded original files in upload tab (dropzone).
