### ISSUE TITLE
Make it easier to find PIN

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#59]
The PIN could be hidden and although be reachable through main interface, not only by entering the help & faq section.

**Comment by dennmuel** [comment]
At the very least it could be formatted bold or colored within the paragraph in the help section.

**Comment by wagneral** [comment]
First approach: https://github.com/UB-Mannheim/PalMA/commit/e64780c3d2bcd432c478f31a021e8378e3cfea9b
