### ISSUE TITLE
"Download this file" for Browser drops the colon from the URI

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/PalMA#6]
Steps to reproduce:

1) Enter `http://www.bib.uni-mannheim.de`
2) Click URL
3) Select the screen with the Browser
4) Click 'Download this file'

=> New tab with `http//www.bib.uni-mannheim.de` (note the dropped `:`)

**Comment by wagneral** [comment]
Fixed by following commit
https://github.com/UB-Mannheim/PalMA/commit/c6b12e11e724e64cff29ee579d080fe9494a4717
