### ISSUE TITLE
Display information/warning when users try to upload a too large file

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#62]
Example file uploaded had about 400 MB. No response from the web interface.

**Comment by wagneral** [comment]
We should perhaps increase the MaxUploadLimit or at least show some kind of notification (e.g. a message box) informing the user about the upload limit

**Comment by stweil** [comment]
It looks like this is a general problem with uploads of files larger than the upload limit (configured for PHP), so I suggest to update the title of this issue.

I vote against increasing the upload limit to a much higher value, because I think that a large upload time is not acceptable. Users can still display large files when they are available via a URL.

**Comment by dennmuel** [comment]
I see your point and agree, but on the other hand users might not have larger files reachable through URL. As wagneral pointed out, a notification and perhaps an explanation/recommendation when to use what sharing method with what kind of files could be helpful.

**Comment by wagneral** [comment]
Came across some dropzone lines, that are responsible for file preview and also for warning users if files are to big. This functionality is disabled: https://github.com/UB-Mannheim/PalMA/blob/master/index.php#L1216

**Comment by wagneral** [comment]
Information is already displayed, but only half a second visible. We should add a delay, so the user has the chance to realize what's happening. 
![error__file-too-big](https://user-images.githubusercontent.com/6931503/30537124-ca85ce8e-9c68-11e7-8fde-d8e4f80b9c85.png)

**Comment by wagneral** [comment]
BTW max_filesize for uploading a file is 256MB

**Comment by wagneral** [comment]
Simple js alert box added. Works.

**Comment by stweil** [comment]
How long does it take to upload 256 MB via a wireless connection? For typical 57 MBit / s connections, maybe 4 MB / s is realistic, so the total time would be 64 s or about 1 minute. Is that acceptable?
