### ISSUE TITLE
Users can't navigate through shared presentations

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#64]
When users upload e.g. a PowerPoint file, they cannot navigate through the slides using the control buttons. The file is displayed with a sidebar showing the structure of the presentation - which is were the cursor is. Assumingly users expect the file to be launched in fullscreen presentation mode. Should we make this the default for this filetype?

**Comment by stweil** [comment]
I think that's even a bug. Of course a presentation must use the whole available window, and it must be possible to navigate.

**Comment by dennmuel** [comment]
I'm sorry if I got something wrong, but I don't quite unterstand the choices for the parameters given to LibreOffice in FileHandler.class.php.
Since LibreOffice by default opens file formats with its corresponding application (ppt with impress, docx with writer, ...), why are there several elseif-clauses that only differ in a parameter for the LibreOffice application?
Also the parameters -n, -o and --view seem to contradict each other - at least I don't get what is supposed to happen, when they are called together like this. (See also: https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters).
Could someone please clarify, if all this is intentional and if so how it is supposed to work?

**Comment by wagneral** [comment]
I completely agree, seems confusing at this point. I'd propose to check the behaviour <b>without</b> the -n -o arguments.

**Comment by dennmuel** [comment]
Please see the quick fix #70. I would like to experiment with automatic conversion to PDF to smoothen the display even further.

**Comment by dennmuel** [comment]
Please see #71, where I implemented an automatic conversion to PDF. In case something goes wrong, the original office files will be displayed as it used to be.
