### ISSUE TITLE
Test navigation on HTML presentations

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/PalMA#66]
I guess that HTML presentation, e.g. with reveal.js, will just work as every website can be displayed. Can we test that the navigation with the arrow keys somehow works?

Examples for such a presentation: http://lab.hakim.se/reveal-js/ and http://www.slides.com/zuphilip/staff-week-2017

**Comment by wagneral** [comment]
The mentioned URL can be used as other URLs as well. Simply paste URL in input form, then the contents can be viewed and controlled by the Palma UI.

Seems not necessary to integrate another JS library for this use case.

**Comment by zuphilip** [comment]
The navigation by keyboard uses the arrow keys: ➡️ , ⬅️ , ⬇️ , ⬆️ . If these keys in at the palma interface will also switch to the next slides etc. then this works fine. Usually, the JS and CSS files are linked and there should not be any need to copy them separately somewhere.

**Comment by dennmuel** [comment]
Arrow keys also work properly as long as the HTML presentation is in the first display - just as with any other shared website.
