### ISSUE TITLE
Dropzone Update

### ISSUE THREAD

**Issue by wagneral** [UB-Mannheim/PalMA#67]
Advanced functionalities should be tested by updating the integrated Dropzone Javascript framework, e.g. for alert messages when uploading big files.

**Comment by dennmuel** [comment]
Also relevant for #88. An "in progress" bar or icon would be nice for uploads. Also currently both success-mark and error-mark are beeing displayed while uploading.

**Comment by wagneral** [comment]
Updated the Dropbox library. Keeping progress bar idea in mind.
