### ISSUE TITLE
Screensaver gets killed on start

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#69]
When PalMA starts `screensaver.php` gets called, but disappears immediately. This repeats a couple of times in a row before it finally stays up. This has happened on physical as well as virtual machines.
/tmp/Palma.log:
```
2017-05-30 10:00:34 start dwb with screensaver
palma: db file = /var/www/html/palma.db
palma: cmd=DISPLAY=:1 HOME=/var/www wmctrl -l, result=
Received SIGSEGV, trying to clean up.
Segmentation fault
2017-05-30 10:00:39 dwb was killed
```

**Comment by dennmuel** [comment]
The problem really seems to be linked to dwb. It did not appear while testing other browsers.

**Comment by stweil** [comment]
Then a quick solution would be using a different browser for the screen saver.
Debugging and fixing dwb would be optional (maybe we have sporadic problems with dwb as a viewer as well).

**Comment by stweil** [comment]
It is possible to write core dumps for each crash. See command `ulimit` which could be used from the start script for more information.

Such core dumps could be used for debugging and also for counting the frequency of the problem.

**Comment by dennmuel** [comment]
We are already committed to changing the browser, so this issue would resolve itself anyway, just as you suggested in your first answer.

**Comment by wagneral** [comment]
Ok, seems to work. Can't find any further problems.
