### ISSUE TITLE
Fix and overhaul responsive design

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#73]
The UI seems to be unfunctional on mobile devices at times. Anyway the responsive design must be adapted to the changes made in #58 and its depending issues respectively.

**Comment by dennmuel** [comment]
Quite a few changes were made in the new-ui branch. Besides some details the new interface could be run through some usability tests with people outside of our core group.

**Comment by wagneral** [comment]
stunning interface btw ;)

**Comment by dennmuel** [comment]
Thank you very much! The basic restructuring has been done and I think we can work on upcoming details (like refitting the help section #45 #93 as well as inputs from usability tests) in the redesign branch, hence the pull request #100.
