### ISSUE TITLE
Change default browser to Firefox / Chromium

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/PalMA#8]
It might be a good idea to use one of the mainstream browsers like Firefox or Chromium as the browser component instead of dwb.

Dwb development is <a href="https://bitbucket.org/portix/dwb/commits/all">very sporadic</a>, Debian updates even less frequent. That means that the WebKit engine embedded is not up-to-date anymore, which can lead to rendering problems and problems with security.

If the browser is required to be lightweight, single-window, keyboard-centric, then there are more actively maintained tools like [uzbl](https://github.com/uzbl/uzbl) or [xombrero](https://github.com/conformal/xombrero).

**Comment by stweil** [comment]
dwb from Debian Jessie was updated on 2014-10-30. It uses libwebkitgtk-3.0-0 with latest update from 2015-03-26, so we can assume that the software is up-to-date.
xombrero uses the same libwebkitgtk-3.0-0, so the rendering will be similar.
ubzl uses libwebkitgtk-1.0-0. I assume that this is an older version than libwebkitgtk-3.0-0.
Up to now, we don't see rendering problems with dwb which don't occur with other browsers, too.

**Comment by stweil** [comment]
dwb updates are still very sporadic, but that is unrelated to the updates of the WebKit engine which is managed in a separate Debian package. Looking at the [https://github.com/WebKit/webkit/commits/master](commits for WebKit), it seems to be well maintained. So can we close this issue?

**Comment by kba** [comment]
You're right, rendering should be fine and up-to-date with Chrome or Opera and other WebKit-based browsers.
