### ISSUE TITLE
Several problems on outdated samsung android smartphone

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#80]
On samsung android smartphone in internet app social media icons are missing. Logut bar floats around. Also there is a small questionmark below the file upload. Dropzone went to fallback mode.

**Comment by dennmuel** [comment]
No work put into this, because the used device (release 2011) and android version (2.3) are outdated and imho not relevant. Therefore closing this issue. (Problems regarding the screensize are beeing tackled.)

**Comment by dennmuel** [comment]
If anybody else would like to take on this issue, they are more than welcome. The core team however will not take on this issue.

**Comment by wagneral** [comment]
As mentioned in different other issues, we will release a list of supported browsers and devices in our documentation.  Therefore closed.
