### ISSUE TITLE
Redesign screensavers

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#89]
Redesign screensavers to emphasize wireless aspect of usage. Maybe add a sequence of pictures to illustrate how the login process works.
Also we will try out new backgrounds on the PalMA station and on the user interface.

**Comment by dennmuel** [comment]
I will be joined by our PR departement to create a new screensaver design. It's most probably going to be one design for all our library departements in order to strengthen PalMA as a "brand" (and therefore hopefully increasing attraction to it) .

**Comment by dennmuel** [comment]
Some drafts have been made. We need to refine them, select our favorites and implement them (php scripts, automatically generated URL and PINs).

**Comment by stweil** [comment]
I suggest to show some additional value to make the screensaver display more attractive. Showing date and time would be interesting (no seconds to avoid too much distraction).

**Comment by dennmuel** [comment]
This has already been noted in the project. I'll discuss this with the PR dept.

**Comment by dennmuel** [comment]
Basic redesign has been made. Decision fell against showing date and time.
Small adjustments might follow, but I think we can consider this task done.
