### ISSUE TITLE
Integrate Reporting Framework

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#92]
In order to improve palma we could collect some data about its usage. We would have to define key values and find a tool to evaluate the most used functions and time periods.

**Comment by dennmuel** [comment]
Piwik has already been implemented in another branch. If it is sufficient or we don't find something better, we can merge it into the redesign branch.

**Comment by wagneral** [comment]
Integration of Piwik is no big deal, right. But we should think about our key values again: maybe ask the library services team about their expectations and then talk about our own experiences in already used and successfully implemented reporting tools .

**Comment by wagneral** [comment]
Think we should release the new palma version first and afterwards merge the piwik branch with the master branch. Let's use the upcoming workshops to ask the library services team about their expectations again and see if piwik is still the right solution.

**Comment by stweil** [comment]
A more general solution would be to optionally include some PHP code which could be part of the theme. Example:

- If `theme/ub-mannheim/a3/index-extra.php` exists, then `index.php` will include it for PalMA stations which use the theme `ub-mannheim/a3`. That optional file could provide any kind of tracking code (not only for Piwik) or even override other aspects of PalMA.

- If there is no `index-extra.php` for the current theme, PalMA will work with the default code (which does not include tracking).

For the rollout of the new PalMA version, some kind of tracking (not necessarily Piwik, but that looks like the easiest option) is more important than ever. How else would the get information about changes in the number of users?

**Comment by wagneral** [comment]
A basic reporting with Piwik is meant to be integrated in the new release of course. Was not sure about a simultaneous rolloaut because I did not look at the piwik branch yet. Can it be merged without conflicts?

Optionally including a reporting framework seems a good idea. Not sure if the theme directory is the right place for it, but can be easily implemented here.

**Comment by stweil** [comment]
The `piwik` branch should not be merged into Git master, because it is special for UB Mannheim. People who get the master branch do not expect to get our Piwik code as well.

**Comment by dennmuel** [comment]
So you would suggest to merge palma-redesign into master and then merge the updated master with our piwik branch, which we then roll out?

On a site note: It would be interesting to see the global usage of PalMA. Would it be legit and doable to have some kind of monitoring of how many active PalMA installations there are worldwide in the master branch? We could then manage our own institutional monitoring with Piwik, theme-dependant `index-extra.php`s or something else.

**Comment by wagneral** [comment]
Should we think about a config parameter for piwik in palma.ini as well? We could add an attribute for enabling piwik and setting a specific piwik key. Or do we have to set different identifiers for each library section / theme?

**Comment by wagneral** [comment]
Config parameter is to specific for common use. There exist a lot of reporting frameworks. So we integrate our custom framework piwik by optionally including PHP codes as hook, as mentioned above.

**Comment by wagneral** [comment]
Piwik hook now included. Ideas for an integrated plugin management are explained in a separate issue.
