### ISSUE TITLE
Refit documentation and help

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#93]
The new release requires us to update the documentation (github wiki) and the user help (help section within palma as well as pdf files on the webpage).
Related to #45

Original note:
Customize documentation when changing interfaces

**Comment by dennmuel** [comment]
Did a quick and dirty update of the help section (133f12b), but the content must be revised. Some icons and/or screenshots would be nice, too.

**Comment by dennmuel** [comment]
We will cooperate with our PR and customer departements to smoothen the wording. (Might take a week or two.) After that we'll take on the translation files.

**Comment by dennmuel** [comment]
Implemented small fixes in the help section suggested by PR. Decision fell against screenshots (at least for now - we'll see how much help is needed).
Still to do/check: readme.md, install.md, wiki, perhaps some handout/walkthrough for our colleagues.

**Comment by wagneral** [comment]
Changed some German translations in PalMA help section. Will check Wiki Sites as well.

**Comment by wagneral** [comment]
- Deleted old documents in `docs/german/*` and `docs/english/*`. Will be replaced by new pdf files with contents of PalMA online help and `INSTALL.md`
- Added `institution_url` to `palma.ini` in `examples` directory
- Added new screenshot to `INSTALL.md` and created a directory for several more screenshots in `docs/images/screenshots`
- Proof-read Wiki contents

**Comment by wagneral** [comment]
PDF Documents uploaded

**Comment by wagneral** [comment]
PDF documents for screensharing uploaded

**Comment by wagneral** [comment]
Documentation complete.
