### ISSUE TITLE
Check input fields for code injection

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#94]

**Comment by wagneral** [comment]
We should not only look for input field security (e.g. sanitizing methods) but generally check for security issues. I'm testing applications like Vega (https://subgraph.com/vega/index.en.html) and 0d1n (https://github.com/CoolerVoid/0d1n).

Perhaps Snyk (https://github.com/marketplace/snyk) from Githubs marketplace could also be interesting.
