### ISSUE TITLE
Javascript not working in IE

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/PalMA#95]
In IE on Win7 sometimes you can only choose a screenlayout, when you have the web developer tools opened. Probably related to [references to the console](https://stackoverflow.com/questions/7742781/why-does-javascript-only-work-after-opening-developer-tools-in-ie-once).
Checking out different branches shows, that this also happens in the master branch.

**Comment by dennmuel** [comment]
Seems like you can only press each button once until you open the console. E.g. you cannot choose a screenlayout on which you had already used before changing to another one. Can't really wrap my head around this yet, so any help is much appreciated.

**Comment by dennmuel** [comment]
Several things seem to be problematic. I already found a workaround for the language selection dropdown JS, but now the feedback form is blocked, because it comes from a different domain (our website and not the palma station).

**Comment by wagneral** [comment]
Microsoft Internet Explorer ist not longer supported. Use Microsoft Edge if necessary.
